In [60]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from xgboost import XGBRFClassifier

In [2]:
diabetes_dataset = pd.read_csv("diabetes.csv")

In [3]:
diabetes_dataset.sample(5)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
444            4      117             62             12        0  29.7   
485            0      135             68             42      250  42.3   
668            6       98             58             33      190  34.0   
210            2       81             60             22        0  27.7   
77             5       95             72             33        0  37.7   

     DiabetesPedigreeFunction  Age  Outcome  
444                     0.380   30        1  
485                     0.365   24        1  
668                     0.430   43        0  
210                     0.290   25        0  
77                      0.370   27        0

In [4]:
diabetes_dataset.shape

(768, 9)

In [5]:
diabetes_dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [6]:
diabetes_dataset["Outcome"].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [7]:
X = diabetes_dataset.drop('Outcome', axis='columns')
y = diabetes_dataset["Outcome"]

In [8]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaler = scaler.fit_transform(X)

In [37]:
X_scaler

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [38]:
X_scaler.shape

(768, 8)

In [39]:
y.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [40]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(sampling_strategy='minority')
X_new, y_new = smote.fit_sample(X_scaler, y)

In [41]:
X_new.shape, y_new.shape

((1000, 8), (1000,))

In [42]:
y_new.value_counts()

1    500
0    500
Name: Outcome, dtype: int64

## Train_model

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y_new, test_size=0.2, stratify=y_new, random_state=2)

In [44]:
X_train.shape, X_test.shape

((800, 8), (200, 8))

In [45]:
y_train.shape, y_test.shape

((800,), (200,))

In [58]:
model = XGBRFClassifier()
model.fit(X_train, y_train)

C:\Users\GIANG LINH\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[23:18:33] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBRFClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
                colsample_bytree=1, enable_categorical=False, gamma=0,
                gpu_id=-1, importance_type=None, interaction_constraints='',
                max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
                monotone_constraints='()', n_estimators=100, n_jobs=4,
                num_parallel_tree=100, objective='binary:logistic',
                predictor='auto', random_state=0, reg_alpha=0,
                scale_pos_weight=1, tree_method='exact', validate_parameters=1,
                verbosity=None)

In [59]:
acc = model.score(X_test, y_test)
acc

0.825

In [48]:
y_pre = model.predict(X_test)

In [49]:
from sklearn.metrics import classification_report

clf = classification_report(y_pre, y_test)

clf

'              precision    recall  f1-score   support\n\n           0       0.80      0.84      0.82        95\n           1       0.85      0.81      0.83       105\n\n    accuracy                           0.82       200\n   macro avg       0.82      0.83      0.82       200\nweighted avg       0.83      0.82      0.83       200\n'

## Making a prediction

In [50]:
input_data = (4,110,92,0,0,37.6,0.191,30)

# changing the input_data to numpy array
input_data_as_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshape = input_data_as_array.reshape(1, -1)

# scale input_data
scale_input_data = scaler.transform(input_data_reshape)

C:\Users\GIANG LINH\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [51]:
scale_input_data

array([[ 0.04601433, -0.34096773,  1.18359575, -1.28821221, -0.69289057,
         0.71168975, -0.84827977, -0.27575966]])

In [52]:
prediction = model.predict(scale_input_data)

In [53]:
prediction

array([0], dtype=int64)

# Saving the trained model

In [54]:
import pickle

In [55]:
# Saving the model in file
filename = 'diabetes_model_deploy.sav'
pickle.dump(model, open(filename, "wb"))

In [56]:
# loading the saved model
loaded_model = pickle.load(open('diabetes_model_deploy.sav', 'rb'))